# active spring boot profile
spring:
   profiles:
      active: dev

---

# common - spring configuration
spring:

   # devtools - live reload
   devtools:
      livereload:
         enabled: true

   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp



---

# dev profile - spring boot configuration

spring:
   config:
      activate:
         on-profile: dev
      
   # datasource
   datasource:
      username: root
      password: root
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/teamproject?characterEncoding=utf8
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

---

# production profile - spring boot configuration
spring:
   config:
      activate:
         on-profile: production

   # datasource
   datasource:
      username: spring
      password: spring
      driver-class-name: org.mariadb.jdbc.Driver
<<<<<<< HEAD
      url: jdbc:mysql://34.64.73.89:3306/spring?characterEncoding=utf8
=======
      url: jdbc:mysql://127.0.0.1:3306/teamproject?characterEncoding=utf8
>>>>>>> a881cc563d725673d9b1518bb53555d070e1e6fc
      hikari:
         minimum-idle: 100
         maximum-pool-size: 200 

---

# server
server:
   port: 8080
   servlet:
     context-path: /
     encoding:
        charset: utf-8
        enabled: true
        force: false
        force-request: false
        force-response: false

---

# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

