# active spring boot profile
spring:
   profiles:
      active: dev   

---

# common - spring configuration
spring:

   # devtools - live reload
   devtools:
      livereload:
         enabled: true

   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp


---

# dev profile - spring boot configuration

spring:
   config:
      activate:
         on-profile: dev
      
  

---

# production profile - spring boot configuration
spring:
   config:
      activate:
         on-profile: production

   # datasource
   datasource:
      username: webdb
      password: blahblha#!@0909#@!
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://227.8.9.10:3306/webdb?characterEncoding=utf8
      hikari:
         minimum-idle: 100
         maximum-pool-size: 200

---

# server
server:
   port: 8888
   servlet:
     context-path: /
     encoding:
        charset: utf-8
        enabled: true
        force: false
        force-request: false
        force-response: false

---


